jwt:
  secret: "7f4c9e2a6b1d8f3c5a7e9b2d4c6f8a1e3b5d7c9f2a4e6b8d1c3f5a7e9b2d4c6"
  expiration-ms: 3600000
server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://microservice_postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    issuer: http://localhost:8082
    expiration: 3600